/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {},
  },
  plugins: [require('daisyui')],
  daisyui: {
    themes: [
      'light',
      'dark',
      {
        light: {
          primary: '#1a73e8',
          'primary-focus': '#1557b2',
          'primary-content': '#ffffff',
          secondary: '#f50057',
          'secondary-focus': '#c50046',
          'secondary-content': '#ffffff',
          accent: '#37cdbe',
          'accent-focus': '#2aa79b',
          'accent-content': '#ffffff',
          neutral: '#3d4451',
          'neutral-focus': '#2a2e37',
          'neutral-content': '#ffffff',
          'base-100': '#ffffff',
          'base-200': '#f9fafb',
          'base-300': '#d1d5db',
          'base-content': '#1f2937',
          info: '#2094f3',
          success: '#009485',
          warning: '#ff9900',
          error: '#ff5724',
        },
        dark: {
          primary: '#389BFF',
          'primary-focus': '#2176CC',
          'primary-content': '#ffffff',
          secondary: '#f472b6',
          'secondary-focus': '#c04b8f',
          'secondary-content': '#ffffff',
          accent: '#4ade80',
          'accent-focus': '#3dae68',
          'accent-content': '#ffffff',
          neutral: '#2a323c',
          'neutral-focus': '#1d232a',
          'neutral-content': '#ffffff',
          'base-100': '#1f2937',
          'base-200': '#111827',
          'base-300': '#0f172a',
          'base-content': '#f3f4f6',
          info: '#0ea5e9',
          success: '#22c55e',
          warning: '#f59e0b',
          error: '#ef4444',
        },
      },
    ],
  },
}; 